version: '2'
services:
  api-gateway:
    image: votasp-api-gateway:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./config:/app/config
    env_file:
      - ../votasp.env
      - ../votasp.env.dev
