swagger: '2.0'
info:
  description: >-
    VotaSP - Questions API. Essa API é responsável por prover 
    as perguntas que serão feitas para candidatos e eleitores.
  version: 1.0.0
  title: VotaSP - Questions API
host: questions.votasp.org.br
basePath: /
schemes:
  - http
paths:
  /questions:
    get:
      summary: Obtém todas as perguntas
      description: ''
      produces:
        - application/json
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
  /answers:
    get:
      summary: Obtém todas as respostas do usuário
      description: ''
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/UserAnswers'
      security:
        - votasp_auth:
            - 'read:answers'
    put:
      summary: Atualiza todas as respostas do usuário
      description: ''
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Array com as respostas do usuário
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Answer'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - votasp_auth:
            - 'write:answers'
    put/{questionId}:
      summary: Atualiza uma das respostas do usuário
      description: ''
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Resposta do usuário
          required: true
          schema:
            $ref: '#/definitions/Answer'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
      security:
        - votasp_auth:
            - 'write:answers'
    delete:
      summary: Remove todas as respostas do usuário
      responses:
        '200':
          description: OK
      security:
        - votasp_auth:
            - 'write:answers'
    delete/{questionId}:
      summary: Remove uma resposta do usuário
      responses:
        '200':
          description: OK
        '404':
          description: Resposta não encontrada
      security:
        - votasp_auth:
            - 'write:answers'
securityDefinitions:
  votasp_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:answers': modificar respostas
      'read:answers': ler respostas
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Question:
    type: object
    properties:
      id:
        type: integer
        format: int64
      version:
        type: integer
        format: int32
      question:
        type: string
  Answer:
    type: object
    properties:
      questionId:
        type: integer
        format: int64
      questionVersion:
        type: integer
        format: int32
      answer:
        type: string
        description: Resposta do usuário à questão
        enum:
          - discordo_plenamente
          - discordo
          - indiferente
          - concordo
          - concordo_plenamente
  UserAnswers:
    type: object
    properties:
      userId:
        type: integer
        format: int64
      answers:
        type: array
        items:
          $ref: '#/definitions/Answer'
externalDocs:
  description: Consulte a especificação completa no repositório de backend
  url: 'https://github.com/Minhacps/votasp-backend'
