version: '2'

services:
  mock-answers:
    image: stoplight/prism
    command: mock --spec api.yml
    volumes:
     - ./mock/api.yml:/api/api.yml
    working_dir: /api
    expose:
     - 4010
  web:
    image: nginx:mainline-alpine
    volumes:
    - ./mock/api.yml:/var/www/api.yml
    - ./mock/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=answers.votasp.local
    - NGINX_PORT=80
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    environment:
      - API_URL=http://answers.votasp.local/api.yml
      - VALIDATOR_URL=null