swagger: '2.0'
info:
  description: >-
    VotaSP - Statements API. Essa API é responsável por prover
    as questões que serão analisadas por candidatos(as) e eleitores(as).
  version: 1.0.0
  title: VotaSP - Statements API
host: statements.votasp.local
basePath: /
schemes:
  - http
paths:
  /:
    get:
      summary: Obtém todas as questões
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Statement'
          examples:
            application/json: |
              [
                {
                    "id": 1,
                    "statement": "Baby, baby do baby do biruleibe leibe."
                },
                {
                    "id": 2,
                    "statement": "O ovo veio antes da galinha."
                },
                {
                    "id": 3,
                    "statement": "Não é um transformers, mas é um bom filme"
                },
                {
                    "id": 4,
                    "statement": "Urso é cultura jovem"
                }
              ]
  /{statementId}:
    get:
      summary: Obtém uma questão
      description: ''
      produces:
        - application/json
      parameters:
        - name: statementId
          in: path
          description: Id da questão
          type: integer
          format: int32
          minimum: 1
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Statement'
          examples:
            application/json: |
              {
                  "id": 1,
                  "statement": "Baby, baby do baby do biruleibe leibe."
              }

definitions:
  Statement:
    type: object
    required:
        - id
        - version
        - statement
    properties:
      id:
        type: integer
        minimum: 1
        format: int32
      statement:
        type: string

externalDocs:
  description: Consulte a especificação completa no repositório de backend
  url: 'https://github.com/Minhacps/votasp-backend/tree/master/api-statements'
