swagger: '2.0'
info:
  description: >-
    VotaSP - Questions API. Essa API é responsável por prover
    as questões que serão analisadas por candidatos e eleitores.
  version: 1.0.0
  title: VotaSP - Questions API
host: questions.votasp.local
basePath: /
schemes:
  - http
paths:
  /:
    get:
      summary: Obtém todas as questões
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
          examples:
            application/json: |
              [
                {
                    "id": 1,
                    "question": "Baby, baby do baby do biruleibe leibe."
                },
                {
                    "id": 2,
                    "question": "O ovo veio antes da galinha."
                },
                {
                    "id": 3,
                    "question": "Não é um transformers, mas é um bom filme"
                },
                {
                    "id": 4,
                    "question": "Urso é cultura jovem"
                }
              ]
  /{questionId}:
    get:
      summary: Obtém uma questão
      description: ''
      produces:
        - application/json
      parameters:
        - name: questionId
          in: path
          description: Id da questão
          type: integer
          format: int32
          minimum: 1
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Question'
          examples:
            application/json: |
              {
                  "id": 1,
                  "question": "Baby, baby do baby do biruleibe leibe."
              }
              
definitions:
  Question:
    type: object
    required:
        - id
        - version
        - question
    properties:
      id:
        type: integer
        minimum: 1
        format: int32
      question:
        type: string

externalDocs:
  description: Consulte a especificação completa no repositório de backend
  url: 'https://github.com/Minhacps/votasp-backend/tree/master/api-questions'
