version: '2'
services:
  questions-api:
    image: votasp-questions:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 30001:30001
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - QUESTIONS_HOST=questions.votasp.local
      - API_PORT=3000
    extra_hosts:
      - "questions.votasp.local:0.0.0.0"
