version: '2'
services:
  questions-api:
    image: votasp-api_answers
    build: .
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - QUESTIONS_HOST=questions.votasp.local
    extra_hosts:
      - "questions.votasp.local:0.0.0.0"
